### ISSUE TITLE
Contenttype quicklink doesn't work

### ISSUE THREAD

**Issue by Sebbe** [LucGosso/Gosso.EPiServerAddOn.QuickNavExtension#5]
Hi, in the solution I work in, the admin page doesn't work without default.aspx. So when I try to use that quicklink then I only get a 404. Adding default.aspx before the url will solve the problem I belive

https://github.com/LucGosso/Gosso.EPiServerAddOn.QuickNavExtension/blob/4ba08bdd0a55189ebe8ba0711b89cef893c6aa09/QuickNavigatorItemProvider.cs#L101

**Comment by LucGosso** [comment]
Added to v2.1 =)

**Comment by Sebbe** [comment]
Thanks!
Was quick to get that to epi feed i see, so tested and can confirm that it works :)
